name: first-demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo action start
        run: echo "Action is running"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello World!"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Action completed
        run: echo "Action completed"
